"""
ml/train_model.py
==================
Train the ransomware detection ML model on the preprocessed dataset.

Models:
  1. RandomForestClassifier  (supervised — learns from labeled ransomware/benign rows)
  2. IsolationForest          (unsupervised — catches zero-day / unseen families)

Ensemble scoring:
  threat_score = 0.70 × P(ransomware | RF) + 0.30 × (1 − IsolationForest_norm)

This formula gives weight to labeled-data confidence (RF) while retaining
anomaly sensitivity for novel variants (IsolationForest).

Output files:
  ml/model.pkl   — serialized model bundle (RF + ISO + scaler)
  ml/scaler.pkl  — StandardScaler (saved separately for inference convenience)
  ml/results.json — full evaluation metrics for the report (Chapter 4)

Dataset: data/dataset.csv (generated by preprocess_ransap.py)
Reference: Hirano et al., RanSAP (Forensic Science International, 2022)

Author: Vedansh Gupta | VIT Vellore
"""

import os
import json
import argparse
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import joblib
import matplotlib
matplotlib.use("Agg")   # non-interactive backend (no display needed)
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier, IsolationForest
from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score, GroupShuffleSplit
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    roc_curve,
    f1_score,
    precision_score,
    recall_score,
    accuracy_score,
)

# ── Feature columns (must match backend/app.py FEATURE_COLS) ─────────────────
# NOTE: updated to match the rewritten preprocess_ransap.py. Removed
# io_read_rate_mb, cpu_percent, rw_ratio, and files_with_entropy_gt7 —
# those were formulas derived from entropy/write-rate, not measured, which
# made feature importance circular (same underlying signal counted 3x).
# Replaced with real storage-trace features: entropy_std, write_rate_mb_s,
# write_events_per_s, read_events_per_s, lba_variance.
FEATURE_COLS = [
    "entropy_mean",
    "entropy_slope",
    "entropy_max",
    "entropy_std",
    "write_rate_mb_s",
    "write_events_per_s",
    "read_events_per_s",
    "lba_variance",
]
LABEL_COL = "label"

DATASET_PATH   = "data/dataset.csv"
MODEL_OUT      = "ml/model.pkl"
SCALER_OUT     = "ml/scaler.pkl"
RESULTS_OUT    = "ml/results.json"
FIGURES_DIR    = "data/sample_logs/figures"


# ── Load & validate ───────────────────────────────────────────────────────────

def load_dataset(path: str) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Dataset not found: {path}\n"
            "Run: python ml/preprocess_ransap.py"
        )

    df = pd.read_csv(path)
    missing = [c for c in FEATURE_COLS + [LABEL_COL] if c not in df.columns]
    if missing:
        raise ValueError(f"Dataset missing columns: {missing}")

    X = df[FEATURE_COLS].values.astype(float)
    y = df[LABEL_COL].values.astype(int)
    groups = df["family"].values if "family" in df.columns else np.arange(len(df))

    print(f"Dataset loaded: {len(df):,} rows | features: {len(FEATURE_COLS)}")
    print(f"  Benign:     {(y==0).sum():,}  ({100*(y==0).mean():.1f}%)")
    print(f"  Ransomware: {(y==1).sum():,}  ({100*(y==1).mean():.1f}%)")
    return X, y, groups


# ── Train ─────────────────────────────────────────────────────────────────────

def train(X_train, y_train, random_state: int = 42):
    """Train RF, XGBoost + IsolationForest. Returns (rf, xgb, iso, scaler)."""

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_train)

    # RandomForest — baseline
    print("\nTraining RandomForestClassifier...")
    rf = RandomForestClassifier(
        n_estimators=100,
        max_depth=8,
        min_samples_split=5,
        min_samples_leaf=2,
        class_weight="balanced",   # handles any remaining class imbalance
        random_state=random_state,
        n_jobs=-1,
    )
    rf.fit(X_scaled, y_train)

    # XGBoost — powerful tree boosting
    print("Training XGBoostClassifier...")
    xgb = XGBClassifier(
        n_estimators=100,
        max_depth=6,
        learning_rate=0.1,
        random_state=random_state,
        n_jobs=-1,
        eval_metric="logloss"
    )
    xgb.fit(X_scaled, y_train)

    # IsolationForest — anomaly detector for zero-day families
    print("Training IsolationForest...")
    iso = IsolationForest(
        n_estimators=100,
        contamination=0.15,        # ~15% of data is anomalous
        random_state=random_state,
        n_jobs=-1,
    )
    iso.fit(X_scaled)

    return rf, xgb, iso, scaler


# ── Evaluate ──────────────────────────────────────────────────────────────────

def evaluate(model, iso, scaler, X_test, y_test, X_all, y_all) -> dict:
    X_test_s = scaler.transform(X_test)
    X_all_s  = scaler.transform(X_all)

    # Model predictions
    y_pred    = model.predict(X_test_s)
    y_prob    = model.predict_proba(X_test_s)[:, 1]

    # Ensemble threat score
    iso_scores = iso.score_samples(X_test_s)
    iso_norm   = np.clip(iso_scores + 0.5, 0, 1)
    threat_scores = 0.70 * y_prob + 0.30 * (1.0 - iso_norm)

    # Standard metrics
    acc       = accuracy_score(y_test, y_pred)
    prec      = precision_score(y_test, y_pred)
    rec       = recall_score(y_test, y_pred)
    f1        = f1_score(y_test, y_pred)
    auc       = roc_auc_score(y_test, y_prob)

    # Cross-validation on full dataset
    X_all_s2  = scaler.transform(X_all)
    cv_scores = cross_val_score(model, X_all_s2, y_all, cv=5, scoring="f1", n_jobs=-1)

    # Feature importance
    if hasattr(model, 'feature_importances_'):
        importances = dict(zip(FEATURE_COLS, model.feature_importances_))
    else:
        importances = {c: 0 for c in FEATURE_COLS}

    metrics = {
        "accuracy":         round(acc,  4),
        "precision":        round(prec, 4),
        "recall":           round(rec,  4),
        "f1_score":         round(f1,   4),
        "roc_auc":          round(auc,  4),
        "cv_f1_mean":       round(float(cv_scores.mean()), 4),
        "cv_f1_std":        round(float(cv_scores.std()),  4),
        "false_positive_rate": round(float(((y_pred == 1) & (y_test == 0)).sum() / max((y_test == 0).sum(), 1)), 4),
        "false_negative_rate": round(float(((y_pred == 0) & (y_test == 1)).sum() / max((y_test == 1).sum(), 1)), 4),
        "test_set_size":    len(y_test),
        "feature_importance": {k: round(float(v), 4) for k, v in importances.items()},
        "confusion_matrix": confusion_matrix(y_test, y_pred).tolist(),
    }

    return metrics, y_prob, threat_scores


# ── Plot figures (for report Chapter 4) ──────────────────────────────────────

def save_figures(rf, scaler, X_test, y_test, y_prob, metrics: dict):
    os.makedirs(FIGURES_DIR, exist_ok=True)

    # Figure 4.2 — ROC Curve
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    fig, ax = plt.subplots(figsize=(6, 5))
    ax.plot(fpr, tpr, color="#1a73e8", lw=2,
            label=f"ROC curve (AUC = {metrics['roc_auc']:.3f})")
    ax.plot([0, 1], [0, 1], "k--", lw=1)
    ax.set_xlabel("False Positive Rate", fontsize=11)
    ax.set_ylabel("True Positive Rate", fontsize=11)
    ax.set_title("Figure 4.2: ROC Curve — RansomShield Detector", fontsize=12, fontweight="bold")
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    fig.savefig(os.path.join(FIGURES_DIR, "roc_curve.png"), dpi=150, bbox_inches="tight")
    plt.close(fig)
    print("  Saved: figures/roc_curve.png")

    # Figure 4.3 — Confusion Matrix
    cm = metrics["confusion_matrix"]
    fig, ax = plt.subplots(figsize=(5, 4))
    im = ax.imshow(cm, cmap="Blues")
    ax.set_xticks([0, 1]); ax.set_yticks([0, 1])
    ax.set_xticklabels(["Benign", "Ransomware"]); ax.set_yticklabels(["Benign", "Ransomware"])
    ax.set_xlabel("Predicted", fontsize=11); ax.set_ylabel("Actual", fontsize=11)
    ax.set_title("Figure 4.3: Confusion Matrix", fontsize=12, fontweight="bold")
    for i in range(2):
        for j in range(2):
            ax.text(j, i, str(cm[i][j]), ha="center", va="center",
                    fontsize=14, color="white" if cm[i][j] > max(cm[0][0], cm[1][1]) / 2 else "black")
    plt.colorbar(im, ax=ax)
    fig.tight_layout()
    fig.savefig(os.path.join(FIGURES_DIR, "confusion_matrix.png"), dpi=150, bbox_inches="tight")
    plt.close(fig)
    print("  Saved: figures/confusion_matrix.png")

    # Feature importance bar
    fi = metrics["feature_importance"]
    sorted_fi = sorted(fi.items(), key=lambda x: x[1], reverse=True)
    labels, vals = zip(*sorted_fi)
    fig, ax = plt.subplots(figsize=(8, 4))
    bars = ax.barh(labels, vals, color="#1a73e8")
    ax.set_xlabel("Importance Score", fontsize=11)
    ax.set_title("Figure 4.4: Feature Importance — RandomForestClassifier", fontsize=12, fontweight="bold")
    ax.invert_yaxis()
    for bar, val in zip(bars, vals):
        ax.text(val + 0.002, bar.get_y() + bar.get_height() / 2,
                f"{val:.3f}", va="center", fontsize=9)
    fig.tight_layout()
    fig.savefig(os.path.join(FIGURES_DIR, "feature_importance.png"), dpi=150, bbox_inches="tight")
    plt.close(fig)
    print("  Saved: figures/feature_importance.png")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset",      default=DATASET_PATH)
    parser.add_argument("--model-out",    default=MODEL_OUT)
    parser.add_argument("--results-out",  default=RESULTS_OUT)
    parser.add_argument("--test-size",    type=float, default=0.20)
    parser.add_argument("--seed",         type=int,   default=42)
    args = parser.parse_args()

    print("=" * 60)
    print("  RansomShield — ML Training Pipeline")
    print("  Dataset : RanSAP (Hirano et al., 2022)")
    print("=" * 60)

    X, y, groups = load_dataset(args.dataset)

    # Grouped train/test split to prevent data leakage (same malware family in both sets)
    gss = GroupShuffleSplit(n_splits=1, test_size=args.test_size, random_state=args.seed)
    train_idx, test_idx = next(gss.split(X, y, groups))
    
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]
    
    print(f"\nTrain: {len(X_train):,}  |  Test: {len(X_test):,}")

    rf, xgb, iso, scaler = train(X_train, y_train, random_state=args.seed)

    print("\nEvaluating RandomForest...")
    rf_metrics, rf_prob, rf_threat = evaluate(rf, iso, scaler, X_test, y_test, X, y)
    
    print("Evaluating XGBoost...")
    xgb_metrics, xgb_prob, xgb_threat = evaluate(xgb, iso, scaler, X_test, y_test, X, y)

    print(f"\n{'─'*40}")
    print(f"Benchmarking Results (F1 Score):")
    print(f"  RandomForest: {rf_metrics['f1_score']:.4f}")
    print(f"  XGBoost     : {xgb_metrics['f1_score']:.4f}")
    
    if xgb_metrics['f1_score'] >= rf_metrics['f1_score']:
        print("🏆 XGBoost wins! Selecting XGBoost for deployment.")
        best_model = xgb
        metrics = xgb_metrics
        y_prob = xgb_prob
    else:
        print("🏆 RandomForest wins! Selecting RandomForest for deployment.")
        best_model = rf
        metrics = rf_metrics
        y_prob = rf_prob

    print(f"{'─'*40}")
    print(f"  Accuracy   : {metrics['accuracy']:.4f}")
    print(f"  Precision  : {metrics['precision']:.4f}")
    print(f"  Recall     : {metrics['recall']:.4f}")
    print(f"  F1 Score   : {metrics['f1_score']:.4f}")
    print(f"  ROC AUC    : {metrics['roc_auc']:.4f}")
    print(f"  CV F1 (5k) : {metrics['cv_f1_mean']:.4f} ± {metrics['cv_f1_std']:.4f}")
    print(f"  FPR        : {metrics['false_positive_rate']:.4f}")
    print(f"  FNR        : {metrics['false_negative_rate']:.4f}")
    print(f"{'─'*40}")

    # Save model bundle
    os.makedirs(os.path.dirname(args.model_out), exist_ok=True)
    bundle = {"rf": best_model, "iso": iso, "scaler": scaler}  # mapped as 'rf' to avoid breaking backend code
    joblib.dump(bundle, args.model_out, compress=3)
    joblib.dump(scaler, SCALER_OUT)
    size_kb = os.path.getsize(args.model_out) / 1024
    print(f"\n✓ Model saved: {args.model_out}  ({size_kb:.0f} KB)")

    # Save results JSON (used in report Chapter 4 tables)
    with open(args.results_out, "w") as f:
        json.dump(metrics, f, indent=2)
    print(f"✓ Results saved: {args.results_out}")

    # Save figures
    print("\nGenerating figures...")
    save_figures(rf, scaler, X_test, y_test, y_prob, metrics)

    print("\n✓ Training complete. All outputs ready for Chapter 4 of the report.")


if __name__ == "__main__":
    main()
